export interface PatientRow {
  id: string
  name: string
  initials: string
  age: number
  gender: 'Male' | 'Female'
  lastAppointment: string
  lastAppointmentReason: string
  address: string
}

export const PATIENTS: PatientRow[] = [
  {
    id: 'pat-1',
    name: 'Maria Santos',
    initials: 'MS',
    age: 34,
    gender: 'Female',
    lastAppointment: 'Jun 21, 2026',
    lastAppointmentReason: 'Routine Cleaning',
    address: 'Quezon City, Metro Manila',
  },
  {
    id: 'pat-2',
    name: 'James Cruz',
    initials: 'JC',
    age: 41,
    gender: 'Male',
    lastAppointment: 'Jun 21, 2026',
    lastAppointmentReason: 'Root Canal Follow-up',
    address: 'Makati City, Metro Manila',
  },
  {
    id: 'pat-3',
    name: 'Liza Fernandez',
    initials: 'LF',
    age: 29,
    gender: 'Female',
    lastAppointment: 'Jun 21, 2026',
    lastAppointmentReason: 'Tooth Extraction',
    address: 'Pasig City, Metro Manila',
  },
  {
    id: 'pat-4',
    name: 'Noah Bautista',
    initials: 'NB',
    age: 8,
    gender: 'Male',
    lastAppointment: 'Jun 22, 2026',
    lastAppointmentReason: 'Dental Checkup',
    address: 'Taguig City, Metro Manila',
  },
  {
    id: 'pat-5',
    name: 'Ana Lim',
    initials: 'AL',
    age: 19,
    gender: 'Female',
    lastAppointment: 'Jun 22, 2026',
    lastAppointmentReason: 'Braces Adjustment',
    address: 'Mandaluyong City, Metro Manila',
  },
  {
    id: 'pat-6',
    name: 'Mark Tan',
    initials: 'MT',
    age: 52,
    gender: 'Male',
    lastAppointment: 'Jun 23, 2026',
    lastAppointmentReason: 'Consultation',
    address: 'Manila, Metro Manila',
  },
  {
    id: 'pat-7',
    name: 'Carla Reyes',
    initials: 'CR',
    age: 27,
    gender: 'Female',
    lastAppointment: 'Jun 23, 2026',
    lastAppointmentReason: 'Teeth Whitening',
    address: 'San Juan City, Metro Manila',
  },
  {
    id: 'pat-8',
    name: 'Paolo Mendoza',
    initials: 'PM',
    age: 45,
    gender: 'Male',
    lastAppointment: 'Jun 24, 2026',
    lastAppointmentReason: 'Dental Implant Review',
    address: 'Cebu City, Cebu',
  },
  {
    id: 'pat-9',
    name: 'Grace Villanueva',
    initials: 'GV',
    age: 36,
    gender: 'Female',
    lastAppointment: 'Jun 24, 2026',
    lastAppointmentReason: 'Routine Cleaning',
    address: 'Davao City, Davao del Sur',
  },
  {
    id: 'pat-10',
    name: 'Diego Ramos',
    initials: 'DR',
    age: 31,
    gender: 'Male',
    lastAppointment: 'Jun 24, 2026',
    lastAppointmentReason: 'Cavity Filling',
    address: 'Pasay City, Metro Manila',
  },
  {
    id: 'pat-11',
    name: 'Sofia Garcia',
    initials: 'SG',
    age: 6,
    gender: 'Female',
    lastAppointment: 'Jun 25, 2026',
    lastAppointmentReason: 'Pediatric Checkup',
    address: 'Antipolo City, Rizal',
  },
  {
    id: 'pat-12',
    name: 'Miguel Torres',
    initials: 'MT',
    age: 58,
    gender: 'Male',
    lastAppointment: 'Jun 25, 2026',
    lastAppointmentReason: 'Gum Treatment',
    address: 'Quezon City, Metro Manila',
  },
  {
    id: 'pat-13',
    name: 'Isabel Cruz',
    initials: 'IC',
    age: 23,
    gender: 'Female',
    lastAppointment: 'Jun 25, 2026',
    lastAppointmentReason: 'Wisdom Tooth Consultation',
    address: 'Makati City, Metro Manila',
  },
  {
    id: 'pat-14',
    name: 'Rafael Santos',
    initials: 'RS',
    age: 39,
    gender: 'Male',
    lastAppointment: 'Jun 26, 2026',
    lastAppointmentReason: 'Braces Adjustment',
    address: 'Iloilo City, Iloilo',
  },
  {
    id: 'pat-15',
    name: 'Camille Aquino',
    initials: 'CA',
    age: 33,
    gender: 'Female',
    lastAppointment: 'Jun 26, 2026',
    lastAppointmentReason: 'Tooth Extraction',
    address: 'Baguio City, Benguet',
  },
  {
    id: 'pat-16',
    name: 'Joshua Lim',
    initials: 'JL',
    age: 47,
    gender: 'Male',
    lastAppointment: 'Jun 26, 2026',
    lastAppointmentReason: 'Routine Cleaning',
    address: 'Mandaluyong City, Metro Manila',
  },
]
